name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean --batch-mode --update-snapshots package
      - name: Build runtime environment of jre 
        run: mvn --batch-mode --update-snapshots javafx:jlink
      - name: Package app image
        run:  mvn exec:exec@image
      - uses: actions/upload-artifact@v3
        with:
          name: windows_x86_app
          path: ece550asm*